### ISSUE TITLE
Compiling error with Godot 2.1.3

### ISSUE THREAD

**Issue by Gramps** [Faless/godot-enet-better#2]
I get the following error when trying to compile the 2.1 branch with Godot 2.1.3:

`modules\benet\enet\godot.cpp(111): error C2039: 'set_blocking_mode': is not a member of 'PacketPeerUDP'`

If I remove that line, instead of tinkering with the Godot core code, I get the following error trying to compile:

`modules\benet\enet_packet_peer.cpp(622): error C2440: '=': cannot convert from 'void' to 'int'`

**Comment by Faless** [comment]
To compile for 2.1 you still need to apply 2 small patches to Godot Core:
You will find the patches in the `patch` folder in the 2.1 branch.
 https://github.com/Faless/godot-enet-better/tree/2.1/patch

I'll PR those patches to godot 2.1 branch at some point (they are backports from master) I'm waiting to PR all the network fixes together

**Comment by Gramps** [comment]
Ah, OK, thanks for the heads up.  That makes sense.   And excuse my ignorance, it is sometimes vast, but how do you use the patches?

**Comment by Gramps** [comment]
Yep, totally spaced that.  Git patches.  Those definitely worked, thanks for the information, sir!

**Comment by Faless** [comment]
Just an update, the patches are now merged in the `2.1` branch of Godot Engine.
You should be able to build the module without patching in that branch and the future `2.1.4` release

**Comment by Gramps** [comment]
Awesome, good to know!  Thank you for the update, sir!

**Comment by Gramps** [comment]
Are they moving ENet back into 2.1.4, hopefully?

**Comment by Faless** [comment]
> Are they moving ENet back into 2.1.4, hopefully?

I don't think so, it's a 3.0 feature, I don't expect it to be backported
