### ISSUE TITLE
About create_server and create_client

### ISSUE THREAD

**Issue by perdugames** [Faless/godot-enet-better#3]
I am confused with the module, you create a server with ip that is taken from the machine ip, then on the client you have the option to put the address, which is to create the client at that address, right, but it arrives in the part to connect , And you connect it to the variable "host", but "host" is in your machine, not able to view it between two or more machines, I will have to create one server, and the other two clients, But how would it connect it to the server, if the "host" gets the ip of the machine?

If I want to do a P2P, can I create multiple servers and connect to each other and just send broadcast between them?

**Comment by Faless** [comment]
I'm not sure I understand your question.
You just need to call create_client(SERVER_IP, SERVER_PORT,
NUMBER_OF_CHANNELS) to connect to the given server ip/port

**Comment by perdugames** [comment]
I'm getting here, my question was a bit ambiguous, it's difficult to express. I'm implementing with your module, and at the same time finishing mine just by studying even XD 

And another doubt that I appeared here now testing the module, Enet was to work also on android I am right?

**Comment by Faless** [comment]
Check out Godot's core/ustring.h
I normally use
String s;
char *c = s.utf8().get_data();

**Comment by Faless** [comment]
> And another doubt that I appeared here now testing the module, Enet was to work also on android I am right?

Yes it should, you need the Internet permission on android of course. I have not tested it though
