### ISSUE TITLE
ENetPacketPeer and ENetNode locks the node in which it is or is called

### ISSUE THREAD

**Issue by perdugames** [Faless/godot-enet-better#4]
I'm having another problem, I can not do this:

`Var enetNode = ENetNode.new ()
`

or

`Var peer = ENetPacketPeer.new ()
`

When testo in the editor works, but when I compile (tested X11 64 and 32, and android) does not work, it hangs the script in which one of these lines is, whether in singleton script or not. Specifically I tested putting the line on a button or calling some variant of a global script in the button script, and it happens to hang, the button is like it did nothing.

**Comment by Faless** [comment]
Did you compile the export templates with the module enabled? Are you sure
you are exporting the game with the right template? Can you provide a
sample project to test?
It works perfectly fine for me in release mode, I'm currently using it in
my steam game tested Windows Linux OSX, never had had crashes or hicups

**Comment by perdugames** [comment]
I do not understand what you mean by compiling with the activated module, is not it just putting in the modules folder and changing the other scripts that are needed and compiling normally? I am not using as a package module, I am using it directly as a new godot. I am sending a test project, just exeperimente comment the lines ENetPacketPeer and ENetNode and export that the button works, but the opposite not, although it works in the test editor.

Is testAndroid but the executable is for X11 64, it is also in the project folder.

[testeAndroid.zip](https://github.com/Faless/godot-enet-better/files/1170351/testeAndroid.zip)

How I am doing:

1 - Down the module of your git
2 - Copy the module folder and paste into the "modules" folder of godot 2.1.3
3 - Altero the files (those that you passed me in the issue of godot)
4 - Compile with "scons platform = x11 bits = 64 builtin_openssl = yes"  or  "scons platform = x11 builtin_openssl = yes"(So Godot closes in the splash).
5 - I open the executable and create the project, it works normally in the test editor but when I export no.

**Comment by Faless** [comment]
@PerduGames you need to build the export templates with the module too if you want to export.
And replace the one you have in .godot/templates with the new generated one (or use the override when exporting).
Have a look at:
http://docs.godotengine.org/en/stable/development/compiling/compiling_for_android.html#building-the-export-templates
http://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html#building-export-templates

**Comment by perdugames** [comment]
I got it here. I misunderstood the documentation. I thought compiling with the module, it would already be together in the executable that is generated. But now it's right, I just have not been able to communicate the computer with the android, but I think it's the door, I'm trying to release it on both devices.

**Comment by perdugames** [comment]
[multiplayer.txt](https://github.com/Faless/godot-enet-better/files/1171982/multiplayer.txt)

I am doing this by using a singleton script that depending on your choice you are server or client, however I get this error:

`ERROR: create_client: Condition ' active ' is true. returned: ERR_ALREADY_IN_USE
   At: modules/benet/enet_packet_peer.cpp:81.
`

I have a button to create the server and one for the client, then I create the server on one computer, and then I try to create the client on another with the ip of the server but I get the error above.

**Comment by Faless** [comment]
The error says that the packet peer is already active, which means you have already called `create_server` or `create_client` on that object.
You can't of course use the same object for the client and the server, you must use 2 separate ENetPacketPeer and/or ENetNode.
Again, check the demo for reference

**Comment by perdugames** [comment]
But it will be two, one on each computer.

**Comment by Faless** [comment]
> But it will be two, one on each computer.

The error says that the packet peer is already active, which means you have already called create_server or create_client on that object.

**Comment by perdugames** [comment]
Then it should be connected. But I did not get anything on the new client connected signal. Devo is doing something wrong.

**Comment by Faless** [comment]
In your code you are using the same `peer` for both the client and the server. This is fine is you only call `createServer` on one machine and only `createClient` on the other. If you call both functions on the same machine it will spit that error.
Additionally, if you call `createClient` or `createServer` more than once on the same machine it will spit that error.

**Comment by perdugames** [comment]
I understood, it must be because I clicked more than once then, but I still could not find why I did not receive the client's connected signal.

**Comment by Faless** [comment]
> I still could not find why I did not receive the client's connected signal.

Please read the README:
```
ENetNode: Act like SceneTree:
Emit signals on idle/fixed time (must be in tree to work!)
```
You do not add the ENetNode to the tree in your example: `add_child(enetNode)` in the `_ready()` function

**Comment by perdugames** [comment]
It's really, since I'm bad, I'd forgotten that. I'm going to change now.

**Comment by PerduGames** [comment]
I added in the tree the _ready() like this:

`get_tree().get_root().add_child(enetNode)
`

It's not going, am I doing it right?

**Comment by perdugames** [comment]
There is a simple way to deal with RawArray, because if its elements range from 0 to 255 it would be more complicated to send the position of the player for example, would have to prick the value or use another element for counting, am I right? Or is there a simple way to do it already?

**Comment by Faless** [comment]
RawArray is just an array of bytes. Godot has `var2bytes` ( http://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-var2bytes ) to convert base types to bytes, but I prefer to use my own conversion so I can optimize the size for what's really needed.

Godot 3.0 has a dedicated class for that `StreamPeerBuffer` (http://docs.godotengine.org/en/latest/classes/class_streampeerbuffer.html#class-streampeerbuffer) but it's not backported to 2.1

**Comment by perdugames** [comment]
Here you put "send_ordered (1 ...)" is this 1 the default for the server?

I'm getting this error "Invalid Target Peer: 1" here:

`ERR_FAIL_V(ERR_INVALID_PARAMETER);
Error ENetPacketPeer::put_packet_channel(..
`

But I'm agreeing that this is the standard for the server, but I may be wrong.

From what I've seen here, it's not sending, how do I send message from client to server?

**Comment by Faless** [comment]
Yes, server is guaranteed to have ID 1.

**Comment by Faless** [comment]
> From what I've seen here, it's not sending, how do I send message from client to server?

Please read the README and check the demo project.
All the info you asked until now are there, this is not a support forum.
You are probably calling `send_ordered (1 ...)` on the server and not on the client or you are sending before receiving the "connected" signal.

**Comment by PerduGames** [comment]
.I checked and received 1 even, but that error would then be why?

**Comment by PerduGames** [comment]
Sorry, I have no where else to ask for help, I'm just sending after being connected, and I'm also sending parameter 1 only from the client to the server.

**Comment by Faless** [comment]
Well, as said, the demo works, start by copying that and do incremental changes.

If you have troubles with Godot features (what is `RawArray`, adding nodes, how signal works, and so on) I suggest you start by reading the documentation: http://docs.godotengine.org/en/stable/ .

I really have no time to act as a personal teacher, since I'm too busy developing my game. Sorry.
If you find an actual bug feel free to open a new issue.

**Comment by perdugames** [comment]
Sorry. It's that I have nowhere else to ask for help for your module, and sometimes we hit the same point, and it takes just one line to look at another point. My browser has at least 10 pages of open doc, I'm always reading, but I understand, I'll find myself here. Thanks for all the help so far.

And you said of your steam game, what would it be? I would like to meet you.

**Comment by Faless** [comment]
The store page is not yet available, I'm planning to release before end of the year.
My (recently created) twitter page is here if you want to follow the development: https://twitter.com/AequitasOrbis

You'll probably find me at the next Godot event in Europe, likely FOSDEM 2018
