### ISSUE TITLE
Benet and Scenetree.

### ISSUE THREAD

**Issue by hungrymonkey** [Faless/godot-enet-better#7]
From the looks of it, the channels are merged into one buffer. 

I presume I would have to make changes to Scenetree to allow different channels for personal uses in order to use godot high level networking

https://godotengine.org/article/godots-new-high-level-networking-preview

Otherwise, I would have to roll my own networking solution.

**Comment by Faless** [comment]
> From the looks of it, the channels are merged into one buffer.

The engine uses only 2 channels (one for reliable, one for unreliable).

You can use this peer with custom data and custom channels while still maintaining compatibility with engine (`_put_packet_channel` automatically uses the first non reserved channel, i.e. the number you give + `SYSCH_MAX`).

If you want the engine to use multiple channels for RPC you have to hack it.

I'll be working on allowing customization for the high level multiplayer without hacking the engine as I have reached a consensus with other Godot devs, so hopefully it should be possible in a not-so-distant future.

P.S: sorry for the delay, I was at FOSDEM and then GodotCon and didn't have much time to give you a proper reply earlier.

**Comment by hungrymonkey** [comment]
@Faless  that happens. thanks for the good work on networking. I actually dont need multiple channel godot RPC. I really need the extra channels to add other networking servers like voice chat. I can use your suggestions when I come back to it. Right now, I am doing a bad hack of using multiple enet networking

**Comment by hungrymonkey** [comment]
May I ask something? I forgot to ask how to query packets from other channels

I see a _put_packet_channel. Is there something like get_packet_channel or something

**Comment by hungrymonkey** [comment]
or do we use EnetNode and basically use those signals

**Comment by hungrymonkey** [comment]
@Faless   Is it possible to have a separate thread querying the network server to grab an channel not used by the game
